name: bkunifylogbeat
version: 7.5.1
description: 蓝鲸日志采集器
description_en: BlueKing Log Collector
scenario: 计算平台，蓝鲸监控，日志检索等和日志相关的数据. 首次使用插件管理进行操作前，先到日志检索/数据平台等进行设置插件的功能项
scenario_en: BKData, BKMonitor, BKLog and other data collection related to logs. For the first use, you need to go to the corresponding platform to set up related function items
category: official
config_file: bkunifylogbeat.conf
config_format: yaml
launch_node: all
auto_launch: 0
is_binary: 1
use_db: 0
config_templates:
  - plugin_version: "*"
    name: bkunifylogbeat.conf
    version: 1
    file_path: etc
    format: yaml
    is_main_config: 1
    source_path: etc/bkunifylogbeat_main.conf.tpl
    variables:
      type: object
      title: variables
      properties:
        extra_vars:
          title: extra_vars
          type: object
          properties:
            max_procs:
              title: "MaxProcs(最大进程数)"
              type: number
            file_identifier:
              title: "FileIdentifier(文件识别模式)"
              type: string
  - plugin_version: "*"
    name: bkunifylogbeat.conf
    version: 1
    file_path: etc/bkunifylogbeat
    format: yaml
    source_path: etc/bkunifylogbeat.conf.tpl
  - plugin_version: "*"
    name: bkunifylogbeat_redis_slowlog.conf
    version: 1
    file_path: etc/bkunifylogbeat
    format: yaml
    source_path: etc/bkunifylogbeat_redis_slowlog.conf.tpl
  - plugin_version: "*"
    name: bkunifylogbeat_syslog.conf
    version: 1
    file_path: etc/bkunifylogbeat
    format: yaml
    source_path: etc/bkunifylogbeat_syslog.conf.tpl
  - plugin_version: "*"
    name: bkunifylogbeat_kafka.conf
    version: 1
    file_path: etc/bkunifylogbeat
    format: yaml
    source_path: etc/bkunifylogbeat_kafka.conf.tpl
control:
  start: "./start.sh bkunifylogbeat"
  stop: "./stop.sh bkunifylogbeat"
  restart: "./restart.sh bkunifylogbeat"
  reload: "./reload.sh bkunifylogbeat"
  version: "./bkunifylogbeat -v"
