name: Build
on:
  push:
    branches: [master, stag]
    paths:
      - '**'
  pull_request:
    branches: [master, stag]
    paths:
      - '**'
  schedule:
    - cron: "0 10 * * *"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Build
        run: |
          make
          ./bin/bkunifylogbeat -v
          CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o bin/bkunifylogbeat-linux-386
          CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o bin/bkunifylogbeat-windows-386.exe
          rm -rf ./bin
