name: Build
on:
  push:
    branches: [master, stag]
    paths:
      - '**'
  pull_request:
    branches: [master, stag]
    paths:
      - '**'
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Build
        run: |
          make
          ./bin/bkunifylogbeat -v
          rm -rf ./bin